"""Add customer portal accounts

Revision ID: a01005fc1121
Revises: 685cab019367
Create Date: 2022-06-20 23:02:04.949826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a01005fc1121'
down_revision = '685cab019367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_portal_accounts',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('price_list_prices')
    op.drop_table('quote_plagues')
    op.drop_table('price_list_plagues')
    op.create_unique_constraint(None, 'companies', ['slug'])
    op.create_unique_constraint(None, 'job_centers', ['slug'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'job_centers', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_table('price_list_plagues',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('price_list_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('plague_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='price_list_plagues_pkey')
    )
    op.create_table('quote_plagues',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('quote_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('plague_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='quote_plagues_pkey')
    )
    op.create_table('price_list_prices',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('price_list_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('scale', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_one', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('price_two', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'price_list_id', name='price_list_prices_pkey')
    )
    op.drop_table('customer_portal_accounts')
    # ### end Alembic commands ###
