name_index = 'Listar países'
name_show = 'Obtener país por ID'
name_store = 'Crear país'
name_update = 'Editar país'
name_destroy = 'Eliminar país'

desc_index = 'Regresa una lista paginada de todos los países o realiza una búsqueda de acuerdo a parámetros.'
desc_show = 'Regresa el objeto "Country" relacionado al id especificado.'
desc_store = 'Registra un nuevo país en el catálogo de Países.'
desc_update = 'Actualiza la información de un país existente, asignando los valores de los parámetros enviados.'
desc_destroy = 'Elimina el país de forma temporal. Internamente solo se actualiza el campo "is_deleted" a False.'
