title_id = 'ID'
title_name = 'Nombre del descuento'
title_description = 'Descripción del descuento'
title_percentage = 'Porcentaje del descuento'
title_job_center_id = 'ID del centro de trabajo'

desc_id = 'ID del objeto.'
desc_name = 'El nombre del descuento.'
desc_description = 'La descripción del descuento.'
desc_percentage = 'El porcentaje del descuento.'
desc_job_center_id = 'ID del objeto del centro de trabajo.'

ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'Cortesía'
ex_description = 'Descuento del 100%'
ex_percentage = '100'
ex_job_center_id = 'cbce9d10-7d92-4f21-90ff-0b859aa304b5'
