title_id = 'ID'
title_name = 'Nombre del empleado'
title_email = 'Correo electrónico del empleado'
title_company_id = 'ID de la compañia'
title_job_center_id = 'ID del centro de trabajo'
title_job_title_id = 'ID del puesto'
title_color = 'Color del empleado'

desc_id = 'ID del objeto.'
desc_name = 'El nombre del empleado.'
desc_email = 'El correo electrónico del empleado.'
desc_company_id = 'ID del objeto de la compañia.'
desc_job_center_id = 'ID del objeto del centro de trabajo.'
desc_job_title_id = 'ID del objeto del puesto.'
desc_color = 'El color del empleado.'


ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'John Doe'
ex_email = 'abc@gmail.com'
ex_company_id = '6c8fe188-76d8-4f34-8adb-bb97282a25b4'
ex_job_center_id = 'a3bc9a9a-bb3f-4791-bc20-503a89f087ba'
ex_job_title_id = '197af568-fa7a-4710-a333-caf6e1d77ade'
ex_color = '#000000'
