title_id = 'ID'
title_name = 'Nombre del producto/servicio extra'
title_description = 'Descripción del producto/servicio extra'
title_quantity = 'Cantidad del producto/servicio extra'
title_job_center_id = 'ID del centro de trabajo'

desc_id = 'ID del objeto.'
desc_name = 'El nombre del producto/servicio extra.'
desc_description = 'La descripción del producto/servicio extra.'
desc_quantity = 'La cantidad del producto/servicio extra.'
desc_job_center_id = 'ID del objeto del centro de trabajo.'

ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'Extra servicio'
ex_description = 'Servicio adicional'
ex_quantity = '500'
ex_job_center_id = 'cbce9d10-7d92-4f21-90ff-0b859aa304b5'
