title_id = 'ID'
title_name = 'Nombre de la indicación'
title_key = 'Clave de la indicación'
title_description = 'Descripción de la indicación'
title_job_center_id = 'ID del centro de trabajo'

desc_id = 'ID del objeto.'
desc_name = 'El nombre de la indicación.'
desc_key = 'La clave de la indicación.'
desc_description = 'La descripción de la indicación.'
desc_job_center_id = 'ID del objeto del centro de trabajo.'

ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'Bodegas'
ex_key = 'BOD'
ex_description = 'Estimado cliente ...'
ex_job_center_id = 'cbce9d10-7d92-4f21-90ff-0b859aa304b5'
