title_id = 'ID'
title_name = 'Nombre de la lista de precio'
title_key = 'Clave de la lista de precio'
title_hierarchy = 'Jerarquía de la lista de precio'
title_cost = 'Costo de la lista de precio'
title_show_price = 'Mostrar precio'
title_service_type_id = 'ID del tipo de servicio'
title_job_center_id = 'ID del centro de trabajo'
title_plague_id = 'ID de la plaga'

desc_id = 'ID del objeto.'
desc_name = 'El nombre de la lista de precio.'
desc_key = 'La clave de la lista de precio.'
desc_hierarchy = 'La clave de la lista de precio.'
desc_cost = 'El costo de la lista de precio.'
desc_show_price = 'Mostrar precio.'
desc_service_type_id = 'ID del objeto del tipo de servicio.'
desc_job_center_id = 'ID del objeto del centro de trabajo'
desc_plague_id = 'ID de la plaga.'

ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'Mantenimiento'
ex_key = 'ABC123'
ex_hierarchy = 1
ex_cost = 499.99
ex_show_price = True
ex_service_type_id = 'f177911f-d48d-46f8-8fed-3646cc5fa040'
ex_job_center_id = 'cbce9d10-7d92-4f21-90ff-0b859aa304b5'
ex_plague_id = 'c8ed998a-3a6e-4e90-944a-e6147e73ba56'
