title_id = 'ID'
title_name = 'Nombre de la lista de precio'
title_key = 'Clave de la lista de precio'
title_hierarchy = 'Jerarquía de la lista de precio'
title_cost = 'Costo de la lista de precio'
title_frequency_days = 'Días de frecuencia para refuerzo'
title_certificate_expiration_days = 'Días para expiración de certificado'
title_follow_up_days = 'Días para seguimiento'
title_show_price = 'Mostrar precio'
title_disinfection = 'Desinfección'
title_service_type_id = 'ID del tipo de servicio'
title_indication_id = 'ID de la indicación'
title_job_center_id = 'ID del centro de trabajo'
title_plague_id = 'ID de la plaga'
title_cover = 'Base64 de PDF de portada'

desc_id = 'ID del objeto.'
desc_name = 'El nombre de la lista de precio.'
desc_key = 'La clave de la lista de precio.'
desc_hierarchy = 'La clave de la lista de precio.'
desc_cost = 'El costo de la lista de precio.'
desc_frequency_days = 'Los días de frecuencia para refuerzo.'
desc_certificate_expiration_days = 'Los días para expiración de certificado.'
desc_follow_up_days = 'Los días para el seguimiento.'
desc_show_price = 'Mostrar precio.'
desc_disinfection = 'Desinfección'
desc_service_type_id = 'ID del objeto del tipo de servicio.'
desc_indication_id = 'ID del objeto de la indicación.'
desc_job_center_id = 'ID del objeto del centro de trabajo'
desc_plague_id = 'ID de la plaga.'
desc_cover = 'Base64 de PDF de portada.'

ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'Mantenimiento'
ex_key = 'ABC123'
ex_hierarchy = 1
ex_cost = 499.99
ex_frequency_days = 25
ex_certificate_expiration_days = 30
ex_follow_up_days = 45
ex_show_price = True
ex_disinfection = True
ex_service_type_id = 'f177911f-d48d-46f8-8fed-3646cc5fa040'
ex_indication_id = 'fc382422-0784-4c51-9788-79e0718c562b'
ex_job_center_id = 'cbce9d10-7d92-4f21-90ff-0b859aa304b5'
ex_plague_id = 'c8ed998a-3a6e-4e90-944a-e6147e73ba56'
ex_cover = 'JVBERi0xLjcKCjEgMCBvYmogICUgZW50cnkgcG9pbnQKPDwKICAvVHlwZSAvQ2F0YWxvZwogIC9QYWdlcyAyIDAgUgo+PgplbmRvYmoKCjIgMCBvYmoKPDwKICAvVHlwZSAvUGFnZXMKICAvTWVkaWFCb3ggWyAwIDAgMjAwIDIwMCBdCiAgL0NvdW50IDEKICAvS2lkcyBbIDMgMCBSIF0KPj4KZW5kb2JqCgozIDAgb2JqCjw8CiAgL1R5cGUgL1BhZ2UKICAvUGFyZW50IDIgMCBSCiAgL1Jlc291cmNlcyA8PAogICAgL0ZvbnQgPDwKICAgICAgL0YxIDQgMCBSIAogICAgPj4KICA+PgogIC9Db250ZW50cyA1IDAgUgo+PgplbmRvYmoKCjQgMCBvYmoKPDwKICAvVHlwZSAvRm9udAogIC9TdWJ0eXBlIC9UeXBlMQogIC9CYXNlRm9udCAvVGltZXMtUm9tYW4KPj4KZW5kb2JqCgo1IDAgb2JqICAlIHBhZ2UgY29udGVudAo8PAogIC9MZW5ndGggNDQKPj4Kc3RyZWFtCkJUCjcwIDUwIFRECi9GMSAxMiBUZgooSGVsbG8sIHdvcmxkISkgVGoKRVQKZW5kc3RyZWFtCmVuZG9iagoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDEwIDAwMDAwIG4gCjAwMDAwMDAwNzkgMDAwMDAgbiAKMDAwMDAwMDE3MyAwMDAwMCBuIAowMDAwMDAwMzAxIDAwMDAwIG4gCjAwMDAwMDAzODAgMDAwMDAgbiAKdHJhaWxlcgo8PAogIC9TaXplIDYKICAvUm9vdCAxIDAgUgo+PgpzdGFydHhyZWYKNDkyCiUlRU9G'
