title_id = 'ID'
title_name = 'Nombre del impuesto'
title_value = 'Valor del impuesto'
title_is_main = 'Impuesto principal'
title_job_center_id = 'ID del centro de trabajo'

desc_id = 'ID del objeto.'
desc_name = 'El nombre del impuesto.'
desc_value = 'El valor del impuesto.'
desc_is_main = 'Em impuesto marcado como principal sera utilizado para cotizaciones y ordenes de servicio.'
desc_job_center_id = 'ID del objeto del centro de trabajo.'

ex_id = '1342f33f-6c9e-408f-b6b0-6f7c507d99d8'
ex_name = 'IVA'
ex_value = '16'
ex_is_main = 'true'
ex_job_center_id = 'cbce9d10-7d92-4f21-90ff-0b859aa304b5'
